project:
  type: website
  output-dir: docs
website:
  title: "please"
  navbar:
    left:
      - href: index.qmd
        projects.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

